
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 65
#define YY_END_OF_BUFFER 66
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[351] =
    {   0,
        0,    0,    9,    9,    0,    0,    0,    0,   66,   64,
       58,   60,   59,   60,   31,    8,   61,   29,   64,   25,
       35,   17,   33,   18,   28,   64,   19,   62,   62,   37,
       27,   16,   22,   61,   61,   26,   36,   41,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   23,   64,   34,    9,   11,   11,
       12,   10,    3,    2,    2,    7,    6,    6,    7,   60,
       30,   61,   61,   15,   57,   38,   63,    0,    4,    1,
       63,    0,    0,    0,   62,    0,   39,   24,   20,   21,
       40,   61,   61,   61,   61,   61,   61,   61,   61,   61,

       61,   61,   61,   61,   57,   61,   61,   61,   61,   61,
       61,   61,   61,   47,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   32,    9,    0,   11,   10,    9,    2,
        6,    5,   63,    0,    0,    0,   63,    0,    0,   63,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   57,   61,   61,   61,   48,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,    0,   63,    0,

       63,    0,    0,   63,   63,    0,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   46,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   13,   54,   61,   61,   63,    0,    0,   63,
        0,   61,   61,   61,   61,   61,   61,   43,   61,   61,
       61,   61,   14,   57,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   57,   61,
       61,   56,    0,   61,   53,   57,   61,   61,   61,   61,
       45,   61,   61,   61,   61,   61,   61,   61,   61,   55,

       51,   52,   61,   61,   61,   61,   44,   57,    0,   61,
       42,   61,   61,   61,   61,   61,   61,   61,   61,   61,
        0,    0,   61,   61,   61,   61,   61,   61,    0,    0,
       61,   61,   61,    0,    0,   61,    0,    0,   61,    0,
        0,    0,    0,    0,    0,    0,    0,   50,   49,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    1,    9,   10,   11,    1,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,    1,   22,   23,
       24,   25,    1,    1,   26,   26,   26,   26,   27,   26,
       26,   26,   28,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   29,   26,   26,   26,   26,   26,   26,   26,
       30,   31,   32,   33,   34,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   26,   44,   45,   46,   47,
       48,   49,   26,   50,   51,   52,   53,   54,   55,   56,
       57,   58,   59,   60,   61,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[62] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    3,    4,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    4,
        4,    1,    1,    1,    1,    4,    4,    4,    4,    1,
        1,    1,    1,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    1,    1,
        1
    } ;

static const flex_int16_t yy_base[358] =
    {   0,
        0,    0,   59,   60,   66,   67,   70,   71,  342, 1078,
     1078, 1078, 1078,  337,  312, 1078,   57, 1078,  318, 1078,
     1078, 1078,  310, 1078,   62,   60,   69,   74,   82, 1078,
       73,  298,   74,   86,   90, 1078, 1078, 1078,   94,   98,
      108,  115,  104,  137,  111,  141,  117,  154,  148,  102,
      157,  150,  119,  174, 1078,  258, 1078,  265, 1078,  291,
     1078,  171, 1078, 1078,  277, 1078, 1078,  259,  238, 1078,
     1078,  106,    0, 1078, 1078, 1078,  199,  200, 1078, 1078,
      176,  207,  215,  170,  222,  224, 1078, 1078, 1078, 1078,
     1078,  185,  227,  230,  232,  234,  239,  243,  245,  247,

      249,  251,  253,  255,  258,  268,  270,  272,  281,  283,
      285,  287,  289,  292,  294,  296,  307,  300,  311,  314,
      318,  324,  329,  336,  341,  343,  348,  353,  355,  360,
      363,  366,  370, 1078,  200,  374, 1078, 1078,  198, 1078,
     1078, 1078,  398,  413,  374,  177,  402,  423,  350,  425,
      427,  429,  379,  431,  434,  436,  440,  443,  447,  450,
      456,  458,  464,  468,  471,  473,  475,  478,  480,  484,
      490,  386,  493,  502,  506,  509,  512,  514,  516,  518,
      522,  525,  534,  531,  539,  543,  545,  547,  549,  553,
      551,  560,  562,  571,  573,  577,  579,  583,  585,  181,

      593,  595,  597,  601,  605,  610,  613,  616,  620,  622,
      625,  627,  629,  632,  635,  637,  640,  644,  647,  649,
      656,  659,  661,  664,  670,  667,  673,  675,  679,  684,
      691,  681,  693,  701,  703,  707,  709,  711,  717,  714,
      719,  721,  723,  727,  732,  737,  739,  743,  165,  745,
      747,  749,  762,  765,  769,  771,  773,  775,  777,  780,
      789,  792,  785,  794,  796,  798,  800,  806,  812,  814,
      816,  820,  823,  828,  832,  838,  841,  843,  845,  851,
      856,  853,  171,  858,  860,  864,  866,  868,  871,  877,
      880,  884,  886,  889,  893,  891,  897,  899,  901,  911,

      913,  919,  921,  924,  926,  928, 1078,  934,  160,  930,
      936,  938,  942,  946,  949,  954,  958,  963,  967,  960,
      137,  131,  970,  975,  977,  980,  982,  984,  141,  121,
      988,  991,  999,  116,  146, 1006,  101,   95, 1008,   95,
       70,   89,   69,   57,   46,   37,   34, 1078, 1078, 1078,
     1057, 1061, 1065,   78, 1069, 1073,   62
    } ;

static const flex_int16_t yy_def[358] =
    {   0,
      350,    1,  351,  351,  352,  352,  353,  353,  350,  350,
      350,  350,  350,  350,  350,  350,  354,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  354,  354,  350,  350,  350,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  350,  350,  350,  355,  350,  350,
      350,  356,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  354,  357,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  354,  354,  354,  354,  354,  354,  354,  354,  354,

      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  350,  355,  350,  350,  350,  355,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  350,  350,  350,

      350,  350,  350,  350,  350,  350,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  350,  350,  350,  350,
      350,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  350,  354,  354,  354,  354,  354,  354,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,

      354,  354,  354,  354,  354,  354,  350,  354,  350,  354,
      354,  354,  354,  354,  354,  354,  354,  354,  354,  354,
      350,  350,  354,  354,  354,  354,  354,  354,  350,  350,
      354,  354,  354,  350,  350,  354,  350,  350,  354,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,    0,
      350,  350,  350,  350,  350,  350,  350
    } ;

static const flex_int16_t yy_nxt[1140] =
    {   0,
       10,   11,   12,   13,   14,   11,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   17,   17,   34,   35,   36,
       10,   37,   38,   17,   39,   40,   41,   42,   43,   44,
       45,   17,   46,   17,   47,   17,   48,   17,   49,   50,
       51,   52,   17,   53,   54,   17,   17,   17,   55,   56,
       57,   59,   59,   60,   60,   73,   61,   61,   64,   64,
       65,   65,   67,   67,   68,   68,   73,   73,   75,   77,
       77,   72,   79,   69,   69,  349,   76,   80,  348,   62,
       62,   81,  347,   82,   82,   87,   88,   90,   91,   81,

       83,   85,   85,  346,   78,   73,   73,   84,   83,   73,
       73,  345,   83,   73,   73,   86,  344,   73,   73,  343,
       83,   73,   73,   73,   73,   73,   73,   73,   73,   95,
       73,   73,   92,  342,   73,   73,   73,   73,   73,   73,
      124,   93,  100,  341,   96,   97,   94,   98,  106,  101,
      107,  340,  102,  104,   99,  103,   73,   73,  113,  108,
       73,   73,  105,  338,  117,  337,  132,   73,   73,   73,
       73,  109,  335,   73,   73,  334,   73,   73,  139,  110,
      114,  111,  121,  330,  112,  329,  115,  116,  118,   82,
       82,  130,  119,   73,   73,  147,  147,  122,  125,  131,

      123,  139,  148,   84,   73,   73,  120,  322,  126,  127,
      139,  128,  307,  129,  148,  133,  283,  139,  143,  143,
      139,  249,  139,  200,   81,  144,   82,   82,  136,  149,
      136,  149,  145,   83,  150,  150,  151,  144,  146,   81,
       84,   85,   85,   85,   85,   83,   73,   73,   83,   73,
       73,   73,   73,   73,   73,   86,  142,   86,   73,   73,
       83,  141,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,  152,   73,   73,  140,
      153,  157,  154,  161,  155,  162,  156,   73,   73,   73,
       73,   73,   73,  137,  164,  136,  158,  159,  160,  163,

       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
      165,   73,   73,   73,   73,   73,   73,  134,  166,   73,
       73,   89,  167,  168,   75,  169,   73,   73,   74,  170,
       73,   73,  171,   73,   73,   71,  172,   73,   73,   70,
      173,  350,  174,   73,   73,  350,  175,  176,   73,   73,
      350,  178,  350,  177,  180,   73,   73,  350,  179,  350,
       73,   73,   73,   73,  183,  172,  181,   73,   73,  150,
      150,  182,   73,   73,   73,   73,  350,  186,  350,   73,
       73,  135,   73,   73,  350,   73,   73,  184,  185,   73,
       73,  350,  187,  143,  143,  189,  188,  193,   73,   73,

      350,  190,  191,  350,  135,   73,   73,  145,  195,  192,
      196,  350,  197,  135,  350,  194,  350,  143,  143,  172,
      135,  201,  201,  135,  144,  135,  350,  198,  148,  198,
      209,  145,  199,  199,  350,  202,  144,  203,  350,  203,
      148,  350,  204,  204,  205,  205,   73,   73,   73,   73,
       73,   73,  350,   73,   73,   73,   73,  350,  206,   73,
       73,  350,   73,   73,  350,  207,   73,   73,  350,   73,
       73,  208,  211,  350,  213,   73,   73,   73,   73,  350,
      212,  172,  210,   73,   73,  172,  214,   73,   73,  350,
       73,   73,   73,   73,   73,   73,  350,   73,   73,   73,

       73,  350,  218,   73,   73,  172,  219,  350,  215,   73,
       73,  220,   73,   73,  216,  217,  221,  350,  223,  350,
      172,   73,   73,  350,  224,   73,   73,  350,   73,   73,
      222,   73,   73,   73,   73,   73,   73,   73,   73,  350,
      172,   73,   73,  350,   73,   73,  225,  228,  350,  226,
       73,   73,  172,   73,   73,  350,  229,  227,   73,   73,
      172,  230,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,  350,  231,  232,  350,  233,   73,
       73,   73,   73,  234,  350,  238,  350,  237,  235,  240,
       73,   73,   73,   73,  236,  350,   73,   73,   73,   73,

      239,  172,  199,  199,  247,  247,  350,  241,  242,  243,
      244,  245,  201,  201,  201,  201,  204,  204,  248,  148,
      250,  250,  350,  246,  205,  205,  202,  350,  202,  205,
      205,  148,   73,   73,  251,   73,   73,  350,  206,   73,
       73,   73,   73,  206,   73,   73,   73,   73,   73,   73,
      350,   73,   73,  252,   73,   73,   73,   73,  254,   73,
       73,  350,  253,   73,   73,  257,   73,   73,   73,   73,
      350,  255,  172,  172,  256,   73,   73,  350,   73,   73,
       73,   73,  259,   73,   73,  258,   73,   73,  172,   73,
       73,  261,   73,   73,   73,   73,  260,  263,   73,   73,

       73,   73,  262,   73,   73,  264,  350,  267,  265,  350,
       73,   73,   73,   73,  350,  172,  266,  350,  270,  272,
       73,   73,   73,   73,  268,  271,   73,   73,   73,   73,
       73,   73,  269,   73,   73,  273,   73,   73,   73,   73,
       73,   73,   73,   73,  350,  276,   73,   73,  350,  275,
      274,   73,   73,  277,  172,  278,   73,   73,  247,  247,
      172,  350,  247,  247,  250,  250,  250,  250,   73,   73,
      350,  280,  248,  279,  350,  282,  248,  350,  251,  350,
      251,   73,   73,  281,   73,   73,  350,  284,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,  350,   73,

       73,  350,  285,  287,   73,   73,  350,  288,   73,   73,
      286,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,  350,  172,  289,  290,   73,   73,  291,  350,  292,
      350,   73,   73,   73,   73,   73,   73,  350,  293,   73,
       73,  294,   73,   73,  350,  296,  295,   73,   73,  172,
      172,   73,   73,  350,  297,  350,  299,   73,   73,  300,
       73,   73,   73,   73,   73,   73,  350,  298,  302,  350,
       73,   73,   73,   73,  301,   73,   73,   73,   73,   73,
       73,  309,  172,   73,   73,   73,   73,   73,   73,  303,
       73,   73,  304,  305,  350,  172,   73,   73,  306,   73,

       73,  350,  310,   73,   73,   73,   73,  308,   73,   73,
       73,   73,   73,   73,  311,  350,   73,   73,   73,   73,
       73,   73,  350,  312,  350,  315,  350,  313,  172,  314,
       73,   73,   73,   73,  172,  172,  350,  172,   73,   73,
       73,   73,  172,   73,   73,   73,   73,   73,   73,   73,
       73,  321,  316,   73,   73,   73,   73,   73,   73,  350,
      317,   73,   73,  350,  319,   73,   73,  350,   73,   73,
      350,  318,  320,   73,   73,  350,  172,   73,   73,   73,
       73,  172,   73,   73,  324,  325,   73,   73,  323,   73,
       73,  350,  326,  350,   73,   73,   73,   73,  172,   73,

       73,   73,   73,   73,   73,  350,  172,   73,   73,  327,
       73,   73,  350,  328,  350,  172,  350,  172,   73,   73,
      350,  331,  332,  350,  333,   73,   73,   73,   73,  350,
      172,  350,  350,  350,  350,  172,  350,  350,  172,  350,
      350,  350,  350,  350,  339,  172,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  336,   58,   58,   58,
       58,   63,   63,   63,   63,   66,   66,   66,   66,  135,
      350,  350,  135,  138,  350,  138,  138,    9,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,

      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350
    } ;

static const flex_int16_t yy_chk[1140] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    3,    4,  357,    3,    4,    5,    6,
        5,    6,    7,    8,    7,    8,   17,   17,   25,   26,
       26,  354,   27,    7,    8,  347,   25,   27,  346,    3,
        4,   28,  345,   28,   28,   31,   31,   33,   33,   29,

       28,   29,   29,  344,   26,   34,   34,   28,   29,   35,
       35,  343,   28,   39,   39,   29,  342,   40,   40,  341,
       29,   50,   50,   43,   43,   72,   72,   41,   41,   39,
       45,   45,   34,  340,   42,   42,   47,   47,   53,   53,
       50,   35,   41,  338,   39,   40,   35,   40,   43,   41,
       43,  337,   41,   42,   40,   41,   44,   44,   45,   43,
       46,   46,   42,  335,   47,  334,   53,   49,   49,   52,
       52,   44,  330,   48,   48,  329,   51,   51,   62,   44,
       46,   44,   49,  322,   44,  321,   46,   46,   48,   84,
       84,   52,   48,   54,   54,   81,   81,   49,   51,   52,

       49,   62,   81,   84,   92,   92,   48,  309,   51,   51,
       62,   51,  283,   51,   81,   54,  249,   62,   77,   77,
       62,  200,   62,  146,   82,   77,   82,   82,  139,   83,
      135,   83,   77,   82,   83,   83,   92,   77,   78,   85,
       82,   85,   85,   86,   86,   82,   93,   93,   85,   94,
       94,   95,   95,   96,   96,   85,   69,   86,   97,   97,
       85,   68,   98,   98,   99,   99,  100,  100,  101,  101,
      102,  102,  103,  103,  104,  104,   93,  105,  105,   65,
       94,   98,   95,  101,   96,  102,   97,  106,  106,  107,
      107,  108,  108,   60,  104,   58,   99,  100,  100,  103,

      109,  109,  110,  110,  111,  111,  112,  112,  113,  113,
      105,  114,  114,  115,  115,  116,  116,   56,  106,  118,
      118,   32,  107,  108,   23,  109,  117,  117,   19,  110,
      119,  119,  111,  120,  120,   15,  112,  121,  121,   14,
      113,    9,  115,  122,  122,    0,  116,  116,  123,  123,
        0,  118,    0,  117,  121,  124,  124,    0,  120,    0,
      125,  125,  126,  126,  123,  119,  122,  127,  127,  149,
      149,  122,  128,  128,  129,  129,    0,  126,    0,  130,
      130,  136,  131,  131,    0,  132,  132,  124,  125,  133,
      133,    0,  126,  145,  145,  128,  127,  131,  153,  153,

        0,  129,  130,    0,  136,  172,  172,  145,  132,  130,
      132,    0,  133,  136,    0,  131,    0,  143,  143,  131,
      136,  147,  147,  136,  143,  136,    0,  144,  147,  144,
      153,  143,  144,  144,    0,  147,  143,  148,    0,  148,
      147,    0,  148,  148,  150,  150,  151,  151,  152,  152,
      154,  154,    0,  155,  155,  156,  156,    0,  150,  157,
      157,    0,  158,  158,    0,  151,  159,  159,    0,  160,
      160,  152,  155,    0,  157,  161,  161,  162,  162,    0,
      156,  158,  154,  163,  163,  159,  160,  164,  164,    0,
      165,  165,  166,  166,  167,  167,    0,  168,  168,  169,

      169,    0,  164,  170,  170,  161,  165,    0,  162,  171,
      171,  166,  173,  173,  163,  163,  168,    0,  170,    0,
      167,  174,  174,    0,  171,  175,  175,    0,  176,  176,
      169,  177,  177,  178,  178,  179,  179,  180,  180,    0,
      173,  181,  181,    0,  182,  182,  174,  176,    0,  174,
      184,  184,  177,  183,  183,    0,  178,  175,  185,  185,
      179,  180,  186,  186,  187,  187,  188,  188,  189,  189,
      191,  191,  190,  190,    0,  181,  182,    0,  183,  192,
      192,  193,  193,  184,    0,  188,    0,  187,  185,  190,
      194,  194,  195,  195,  186,    0,  196,  196,  197,  197,

      189,  191,  198,  198,  199,  199,    0,  192,  193,  194,
      195,  196,  201,  201,  202,  202,  203,  203,  199,  201,
      204,  204,    0,  197,  205,  205,  201,    0,  202,  206,
      206,  201,  207,  207,  204,  208,  208,    0,  205,  209,
      209,  210,  210,  206,  211,  211,  212,  212,  213,  213,
        0,  214,  214,  207,  215,  215,  216,  216,  209,  217,
      217,    0,  208,  218,  218,  212,  219,  219,  220,  220,
        0,  210,  213,  214,  211,  221,  221,    0,  222,  222,
      223,  223,  217,  224,  224,  215,  226,  226,  216,  225,
      225,  219,  227,  227,  228,  228,  218,  222,  229,  229,

      232,  232,  221,  230,  230,  223,    0,  227,  225,    0,
      231,  231,  233,  233,    0,  224,  226,    0,  230,  232,
      234,  234,  235,  235,  228,  231,  236,  236,  237,  237,
      238,  238,  229,  240,  240,  233,  239,  239,  241,  241,
      242,  242,  243,  243,    0,  237,  244,  244,    0,  236,
      234,  245,  245,  239,  235,  240,  246,  246,  247,  247,
      238,    0,  248,  248,  250,  250,  251,  251,  252,  252,
        0,  242,  247,  241,    0,  246,  248,    0,  250,    0,
      251,  253,  253,  245,  254,  254,    0,  252,  255,  255,
      256,  256,  257,  257,  258,  258,  259,  259,    0,  260,

      260,    0,  253,  255,  263,  263,    0,  257,  261,  261,
      254,  262,  262,  264,  264,  265,  265,  266,  266,  267,
      267,    0,  256,  259,  260,  268,  268,  261,    0,  262,
        0,  269,  269,  270,  270,  271,  271,    0,  264,  272,
      272,  265,  273,  273,    0,  268,  267,  274,  274,  266,
      269,  275,  275,    0,  270,    0,  272,  276,  276,  273,
      277,  277,  278,  278,  279,  279,    0,  271,  275,    0,
      280,  280,  282,  282,  274,  281,  281,  284,  284,  285,
      285,  286,  277,  286,  286,  287,  287,  288,  288,  276,
      289,  289,  278,  280,    0,  279,  290,  290,  281,  291,

      291,    0,  287,  292,  292,  293,  293,  284,  294,  294,
      296,  296,  295,  295,  288,    0,  297,  297,  298,  298,
      299,  299,    0,  289,    0,  296,    0,  294,  290,  295,
      300,  300,  301,  301,  292,  297,    0,  298,  302,  302,
      303,  303,  293,  304,  304,  305,  305,  306,  306,  310,
      310,  308,  299,  308,  308,  311,  311,  312,  312,    0,
      303,  313,  313,    0,  305,  314,  314,    0,  315,  315,
        0,  304,  306,  316,  316,    0,  312,  317,  317,  320,
      320,  310,  318,  318,  314,  315,  319,  319,  313,  323,
      323,    0,  316,    0,  324,  324,  325,  325,  320,  326,

      326,  327,  327,  328,  328,    0,  317,  331,  331,  318,
      332,  332,    0,  319,    0,  325,    0,  326,  333,  333,
        0,  323,  324,    0,  327,  336,  336,  339,  339,    0,
      332,    0,    0,    0,    0,  328,    0,    0,  331,    0,
        0,    0,    0,    0,  336,  339,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  333,  351,  351,  351,
      351,  352,  352,  352,  352,  353,  353,  353,  353,  355,
        0,    0,  355,  356,    0,  356,  356,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,

      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "jucompiler.l"
#line 2 "jucompiler.l"
/*
    Luís Neto -2020215474
    João Moura -2020235800 
*/        
//Constantes
    #include <stdio.h>
	#include <stdlib.h>
	#include <string.h>
	#include <stdbool.h>
    #include <stdarg.h>
	#include "y.tab.h"
	#include "semantics.h"
	#define false 0
    #define true 1
    int col=1; 
    int line=1;
    int commentBegin[2];
    int strlitBegin[2];
	extern int flag_erro;
	extern Node* root;
	int printLex=false;
    int doYacc=false;
    char *strlit;
    int str=0;
#line 833 "lex.yy.c"
               
#line 835 "lex.yy.c"

#define INITIAL 0
#define STRLLIT 1
#define LINE_COMMENT 2
#define COMMENT 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 42 "jucompiler.l"


#line 1058 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 351 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1078 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 44 "jucompiler.l"
{BEGIN LINE_COMMENT;}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 45 "jucompiler.l"
{line+=1,col=1,BEGIN 0;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 46 "jucompiler.l"
{col+=yyleng;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 48 "jucompiler.l"
{BEGIN COMMENT;commentBegin[0]=line;commentBegin[1]=col;col+=yyleng;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 49 "jucompiler.l"
{BEGIN 0;col+=yyleng;}
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 50 "jucompiler.l"
{line++;col=1;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 51 "jucompiler.l"
{col+=yyleng;}
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 52 "jucompiler.l"
{BEGIN 0;printf("Line %d, col %d: unterminated comment\n",commentBegin[0],commentBegin[1]);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 54 "jucompiler.l"
{BEGIN STRLLIT;strlit=yytext;strlitBegin[0]=line;strlitBegin[1]=col;col+=yyleng;str=1;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 55 "jucompiler.l"
{col+=yyleng;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 56 "jucompiler.l"
{printf("Line %d, col %d: invalid escape sequence (%s)\n",line,col,yytext); col += yyleng;str = 0;}
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 57 "jucompiler.l"
{line++; col= 1; printf("Line %d, col %d: unterminated string literal\n",strlitBegin[0],strlitBegin[1]);BEGIN 0;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 58 "jucompiler.l"
{if(printLex && str==1)printf("STRLIT(%s)\n",strlit);col+=yyleng;BEGIN 0;
                                                                        if(doYacc && str== 1) {
											                                    yylval.id = strdup(strlit);
																				yytext=strlit;
																				return STRLIT;
										}}
	YY_BREAK
case YY_STATE_EOF(STRLLIT):
#line 64 "jucompiler.l"
{printf("Line %d, col %d: unterminated string literal\n",strlitBegin[0],strlitBegin[1]); col+=yyleng; BEGIN 0;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 67 "jucompiler.l"
{if(printLex)printf("BOOLLIT(true)\n"); col+=yyleng;
                                        if(doYacc) {
											yylval.id = strdup(yytext);
											return BOOLLIT;
										}}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 72 "jucompiler.l"
{if(printLex)printf("BOOLLIT(false)\n"); col+=yyleng;
                                        if(doYacc) {
											yylval.id = strdup(yytext);
											return BOOLLIT;
										}}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 77 "jucompiler.l"
{if(printLex)printf("AND\n"); col+=yyleng;if(doYacc)return AND;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 78 "jucompiler.l"
{if(printLex)printf("ASSIGN\n"); col+=yyleng; if(doYacc)return ASSIGN;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 79 "jucompiler.l"
{if(printLex)printf("STAR\n"); col+=yyleng; if(doYacc)return STAR;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 80 "jucompiler.l"
{if(printLex)printf("COMMA\n"); col+=yyleng; if(doYacc)return COMMA;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 81 "jucompiler.l"
{if(printLex)printf("DIV\n"); col+=yyleng; if(doYacc)return DIV;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 82 "jucompiler.l"
{if(printLex)printf("EQ\n"); col+=yyleng; if(doYacc)return EQ;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 83 "jucompiler.l"
{if(printLex)printf("GE\n"); col+=yyleng; if(doYacc)return GE;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 84 "jucompiler.l"
{if(printLex)printf("GT\n"); col+=yyleng; if(doYacc)return GT;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 85 "jucompiler.l"
{if(printLex)printf("LBRACE\n"); col+=yyleng; if(doYacc)return LBRACE;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 86 "jucompiler.l"
{if(printLex)printf("LE\n"); col+=yyleng; if(doYacc)return LE;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 87 "jucompiler.l"
{if(printLex)printf("LPAR\n");col+=yyleng; if(doYacc)return LPAR;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 88 "jucompiler.l"
{if(printLex)printf("LSQ\n");col+=yyleng; if(doYacc)return LSQ;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 89 "jucompiler.l"
{if(printLex)printf("LT\n");col+=yyleng; if(doYacc)return LT;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 90 "jucompiler.l"
{if(printLex)printf("MINUS\n");col+=yyleng; if(doYacc)return MINUS;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 91 "jucompiler.l"
{if(printLex)printf("MOD\n"); col+=yyleng; if(doYacc)return MOD;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 92 "jucompiler.l"
{if(printLex)printf("NE\n"); col+=yyleng; if(doYacc)return NE;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 93 "jucompiler.l"
{if(printLex)printf("NOT\n");col+=yyleng; if(doYacc)return NOT;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 94 "jucompiler.l"
{if(printLex)printf("OR\n"); col+=yyleng; if(doYacc)return OR;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 95 "jucompiler.l"
{if(printLex)printf("PLUS\n");col+=yyleng; if(doYacc)return PLUS;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 96 "jucompiler.l"
{if(printLex)printf("RBRACE\n");col+=yyleng; if(doYacc)return RBRACE;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 97 "jucompiler.l"
{if(printLex)printf("RPAR\n"); col+=yyleng; if(doYacc)return RPAR;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 98 "jucompiler.l"
{if(printLex)printf("RSQ\n"); col+=yyleng; if(doYacc)return RSQ;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 99 "jucompiler.l"
{if(printLex)printf("SEMICOLON\n"); col+=yyleng; if(doYacc)return SEMICOLON;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 100 "jucompiler.l"
{if(printLex)printf("ARROW\n"); col+=yyleng; if(doYacc)return ARROW;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 101 "jucompiler.l"
{if(printLex)printf("LSHIFT\n"); col+=yyleng; if(doYacc)return LSHIFT;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 102 "jucompiler.l"
{if(printLex)printf("RSHIFT\n"); col+=yyleng; if(doYacc)return RSHIFT;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 103 "jucompiler.l"
{if(printLex)printf("XOR\n"); col+=yyleng; if(doYacc)return XOR;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 104 "jucompiler.l"
{if(printLex)printf("BOOL\n"); col+=yyleng;if(doYacc)return BOOL;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 105 "jucompiler.l"
{if(printLex)printf("CLASS\n"); col+=yyleng;if(doYacc)return CLASS;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 106 "jucompiler.l"
{if(printLex)printf("DOTLENGTH\n"); col+=yyleng;if(doYacc)return DOTLENGTH;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 107 "jucompiler.l"
{if(printLex)printf("DOUBLE\n"); col+=yyleng;if(doYacc)return DOUBLE;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 108 "jucompiler.l"
{if(printLex)printf("ELSE\n"); col+=yyleng; if(doYacc)return ELSE;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 109 "jucompiler.l"
{if(printLex)printf("IF\n"); col+=yyleng;if(doYacc)return IF;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 110 "jucompiler.l"
{if(printLex)printf("INT\n"); col+=yyleng;if(doYacc)return INT;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 111 "jucompiler.l"
{if(printLex)printf("PRINT\n"); col+=yyleng;if(doYacc)return PRINT;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 112 "jucompiler.l"
{if(printLex)printf("PARSEINT\n"); col+=yyleng;if(doYacc) return PARSEINT;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 113 "jucompiler.l"
{if(printLex)printf("RETURN\n"); col+=yyleng;if(doYacc) return RETURN;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 114 "jucompiler.l"
{if(printLex)printf("STATIC\n"); col+=yyleng;if(doYacc)return STATIC;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 115 "jucompiler.l"
{if(printLex)printf("STRING\n"); col+=yyleng;if(doYacc)return STRING;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 116 "jucompiler.l"
{if(printLex)printf("VOID\n"); col+=yyleng;if(doYacc) return VOID;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 117 "jucompiler.l"
{if(printLex)printf("PUBLIC\n"); col+=yyleng;if(doYacc)return PUBLIC;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 118 "jucompiler.l"
{if(printLex)printf("WHILE\n"); col+=yyleng;if(doYacc) return WHILE;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 119 "jucompiler.l"
{if(printLex)printf("RESERVED(%s)\n",yytext); col+=yyleng;if(doYacc) return RESERVED;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 120 "jucompiler.l"
{col+=yyleng;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 121 "jucompiler.l"
{col+=yyleng;}
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 122 "jucompiler.l"
{line+=1; col=1;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 123 "jucompiler.l"
{if(printLex)printf("ID(%s)\n",yytext); col+=yyleng;
                                        if(doYacc) {
											yylval.id = strdup(yytext);
											return ID;
										}}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 128 "jucompiler.l"
{if(printLex)printf("INTLIT(%s)\n",yytext); col+=yyleng;
                                     if(doYacc) {
											yylval.id = strdup(yytext);
											 return INTLIT;
										}}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 133 "jucompiler.l"
{if(printLex)printf("REALLIT(%s)\n",yytext); col+=yyleng;
                                            if(doYacc) {
											yylval.id = strdup(yytext);
											return REALLIT;
										}}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 139 "jucompiler.l"
{printf("Line %d, col %d: illegal character (%s)\n", line,col,yytext); col+=yyleng;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 142 "jucompiler.l"
ECHO;
	YY_BREAK
#line 1477 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(LINE_COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 351 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 351 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 350);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 142 "jucompiler.l"


void yyerror(const char *s) { 
     printf ("Line %d, col %d: %s: %s\n", line, (int)(col-strlen(yytext)), s, yytext);
}

int yywrap() {
	return 1;
}

int main(int argc,char* argv[]){
    if (argc > 1){
        if (strcmp(argv[1], "-l") == 0){
            printLex=true;
            doYacc=false;
            yylex();}
        else if(strcmp(argv[1], "-t") == 0){
            doYacc=true;
			printLex=false;
            yyparse();
			if (flag_erro == 0) {
				printTree(root, 0);
			}else{
				freeTree(root);
			}  
        }
        else if (strcmp(argv[1], "-e1") == 0) {
			printLex=false;
            doYacc=false;
			yylex() ;
         }
        else if (strcmp(argv[1], "-e2") == 0) {
			printLex=false;
            doYacc=true;
			yyparse();
			freeTree(root);
		}
		else if(strcmp(argv[1],"-s")==0){
			doYacc=true;
			printLex=false;
			yyparse();
			check_program(root);
			print_tabela();
			freeTree(root);

		}
	}
    else {
		printLex=false;
        doYacc=true;
		yyparse();
		freeTree(root);
		
	}
	return 0;
}

